# Generated by Django 4.1.7 on 2023-06-17 18:49

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='tarefas',
            fields=[
                ('id_tarefa', models.AutoField(primary_key=True, serialize=False)),
                ('nome_tarefa', models.TextField(max_length=100)),
                ('data', models.DateField()),
                ('hora', models.TimeField()),
            ],
        ),
    ]
