# Generated by Django 4.1.7 on 2023-06-17 19:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_tarefas', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='tarefas',
            new_name='Tarefa',
        ),
    ]
